Repository NumPower/numpower, pull requests merged in 2024-07, with the labels that each got.

#56 NDArray::poisson() 'Argument #2 ($lam) must be of type float, float g…
  numpower.c
  src/initializers.c
  tests/random/002-ndarray-poisson.phpt
Labels: bug

#54 NDArray::standard_normal() 'expects at most 3 arguments' bugfix
  numpower.c
  tests/random/001-ndarray-standard_normal.phpt
Labels: bug

#53 GPU matmul refactoring and optimization
  src/gpu_alloc.c
  src/ndmath/linalg.c
Labels: optimization

#59 fix: destructor causing segmentation fault
  .github/workflows/main.yml
  numpower.c
  tests/random/001-ndarray-standard_normal.phpt
  tests/random/002-ndarray-poisson.phpt
Labels: bug, segfault

#60 fix: segmentation fault with empty arrays initialization and __toString magic method
  numpower.c
  src/debug.c
  src/initializers.c
  tests/initializers/001-ndarray-array-phparray.phpt
Labels: bug, segfault

#61 stubs.php file for the NDArray class
  stubs/numpower.stubs.php
Labels: enhancement

#64 New methods and features for 0.6.0
  README.md
  numpower.c
  php_numpower.h
  src/dnn.c
  src/iterators.c
  src/iterators.h
  src/manipulation.c
  src/manipulation.h
  src/ndarray.c
  src/ndarray.h
  src/ndmath/calculation.c
  src/ndmath/calculation.h
  src/ndmath/cuda/cuda_math.cu
  src/ndmath/cuda/cuda_math.h
  src/ndmath/double_math.c
  src/ndmath/double_math.h
  src/ndmath/linalg.c
  stubs/numpower.stubs.php
  tests/manipulation/003-ndarray-append.phpt
Labels: enhancement
